import CardLayout from '@components/layout/CardLayout'
import PageView from '@components/layout/PageView'
import Intro from '@components/typography/Intro'
import Writing from '@components/typography/Writing'
import Card from '@components/ui/Card'
import Divider from '@components/ui/Divider'

export default function PrivacyPage() {
  return (
    <PageView>
      <CardLayout>
        <Card>
          <Intro
            title={<Intro.Title>Privacy Policy</Intro.Title>}
            subtitle={<Intro.Subtitle>Last updated: May 08, 2023</Intro.Subtitle>}
          />
          <Divider />
          <Writing>
            <p>
              This Privacy Policy describes how I collect, use, and share information when you visit
              or interact with our website (&quot;Site&quot;). By using our Site, you agree to the
              collection and use of information in accordance with this Privacy Policy.
            </p>
            <p>I do not collect any personal information on this site.</p>
          </Writing>
          <Divider />
          <Intro title={<Intro.Title>Information Collection and Use</Intro.Title>} gutterBottom />
          <Writing>
            <p>
              I use Google Analytics 4 to collect and analyze anonymized data about our Site&apos;s
              usage. Google Analytics 4 is a web analytics service provided by Google, Inc.
              (&quot;Google&quot;). Google Analytics 4 uses cookies, which are small text files
              placed on your computer, to help us understand how visitors use our Site. The
              information generated by the cookie about your use of the Site will be transmitted to
              and stored by Google on their servers.
            </p>
            <p>
              Google will use this information for the purpose of evaluating your use of our Site,
              compiling reports on website activity, and providing other services relating to
              website activity and internet usage. Google may also transfer this information to
              third parties where required to do so by law, or where such third parties process the
              information on Google&apos;s behalf.
            </p>
            <p>
              In addition to the default anonymous tracking provided by Google Analytics 4, I also
              collect the following custom events:
            </p>
            <ul>
              <li>When you interact with the &quot;Evidence&quot; checkboxes on our Site</li>
              <li>When you minimize or maximize a ghost type on our Site</li>
              <li>When you solve a ghost type on our Site</li>
            </ul>
            <p>
              These custom events are also collected and processed in an anonymized manner, and they
              help us improve our Site&apos;s functionality and user experience.
            </p>
          </Writing>
          <Divider />
          <Intro title={<Intro.Title>Third-party Websites</Intro.Title>} gutterBottom />
          <Writing>
            <p>
              This Website may contain hyperlinks to websites operated by parties other than us. We
              provide such hyperlinks for your reference only. I do not control such websites and
              are not responsible for their contents or the privacy or other practices of such
              websites. It is up to you to read and fully understand their Privacy Policies. Our
              inclusion of hyperlinks to such websites does not imply any endorsement of the
              material on such websites or any association with their operators.
            </p>
          </Writing>
          <Divider />
          <Intro title={<Intro.Title>User Consent and Opt-Out</Intro.Title>} gutterBottom />
          <Writing>
            <p>
              By using our Site, you consent to the processing of your data by Google in the manner
              and for the purposes set out above. If you wish to opt-out of Google Analytics
              tracking, you can do so by installing the Google Analytics Opt-out Browser Add-on,
              available at:{' '}
              <a
                href="https://tools.google.com/dlpage/gaoptout"
                target="_blank"
                rel="noopener noreferrer"
              >
                https://tools.google.com/dlpage/gaoptout
              </a>
            </p>
          </Writing>
          <Divider />
          <Intro title={<Intro.Title>Changes to This Privacy Policy</Intro.Title>} gutterBottom />
          <Writing>
            <p>
              I may update this Privacy Policy from time to time. I will notify you of any changes
              by posting the new Privacy Policy on this page and updating the &quot;Last
              updated&quot; date at the top of this Privacy Policy. You are advised to review this
              Privacy Policy periodically for any changes. Changes to this Privacy Policy are
              effective when they are posted on this page.
            </p>
          </Writing>
          <Divider />
          <Intro title={<Intro.Title>Contact</Intro.Title>} gutterBottom />
          <Writing>
            <p>If you have any questions about this Privacy Policy, please contact me:</p>
            <ul>
              <li>By email: graysonleegantek@gmail.com</li>
            </ul>
          </Writing>
        </Card>
      </CardLayout>
    </PageView>
  )
}
